<?php 
    //DebugBreak();
    use Zend\Form\Element;
    use Post\Model\Post;
    
    define("LIKE", "Like");
    define("UNLIKE", "Unlike");
    
    $post = new Post();
?>
     
<?php
    //PRINT POSTS
    foreach ($messages as $message) :
?>
    <li id="post-<?php print $message['post_id']; ?>">
        <div class="post-message">
            <div class="message-head">
                <div class="row">
                    <div class="col-sm-2">
                        <img src="<?php print "/img/users/".$message['post_username_img']; ?>" 
                             alt="<?php print $message['post_username']; ?>"
                        >                    
                    </div>
                    <div class="col-sm-8">
                        <span class="author">
                            <?php print $message['post_username']; ?>
                        </span>
                        <span class="time">
                            <?php print 
                            $this->postTime($message['post_time']) ?>
                        </span>
                    </div>
                </div>
                <div class="row">
                    <div class="liked col-sm-12">
                <?php 
                    $likes = explode(',',$message['post_like_usernames']);
                    $likeString = LIKE;
                    
                    if ((!empty($message['post_like_usernames'])) 
                        && count($likes) > 0) { 
                            if (in_array($userSession->username, 
                                $likes)) {
                                $likeString = UNLIKE;                        
                            }

                            print $this->partial('partial/likes.phtml', array(
                                'likes'       => $likes,
                                'userSession' => $userSession,
                                'postType'    => $message['post_type'],
                            ));
                            /*print $this->printLikedBy(
                                $likes, 
                                
                            );*/
                    }
                ?>
                    </div>
                </div>

            </div>
            <?php if ($message['post_username'] == 
                          $userSession->username) {?>
                     <a href="javascript:void(0)" 
                        rel="edit-post">Edit Post</a>
            <?php } ?> 
            <div class="message-body">
                <div class="message">
                    <?php print $message['post_message']; ?>
                </div>
                <div class="row">
                    <div class="files col-sm-12">
                        <?php
                            $oldFileNames = explode(',',$message['post_file_old_names']);
                            $newFileNames = explode(',',$message['post_file_new_names']);
                            
                            if ((!empty($message['post_file_new_names'])) 
                                && count($newFileNames) > 0) {
                        ?>
                            <div class="row">
                                <div class="files col-sm-12">                    
                            <?php    
                                $files = array();
                                $images = array();
                                
                                for($i=0 ;$i<count($newFileNames); ++$i){
                                    $newName = $newFileNames[$i];
                                    $oldName = $oldFileNames[$i];
                                    $files[$newName] = $oldName;     
                                }
                                
                                foreach ($files as $new => $old) {
                                    $fileType = strtolower(pathinfo(basename($new),
                                                PATHINFO_EXTENSION));
                                    
                                    if($fileType == "jpg" || $fileType == "png"
                                        || $fileType == "gif") {
                                       $images[] = $new;     
                                    }
                                    print "<a class='".$fileType."' 
                                            href='/posts/".$new."'
                                            target='_self' 
                                            download>".$old.
                                    "</a>";
                                    
                                } 
                            ?>
                                </div>
                            </div>
                        <?php
                            }
                        ?>                    
                    </div>
                </div>
                <?php if(isset($images) && count($images) > 0)  { ?>
                    <div class="row">
                        <div class="img-files col-sm-12">
                            <?php
                                 foreach ($images as $img) {
                                     print "<a class='fancybox' href='/posts/".$img."'       
                                            target='_self'>";
                                     print "<img  
                                            src='/posts/".$img."'
                                            alt='".$img."' 
                                            />";
                                     print "</a>";                                 
                                 }
                                 unset($images);                                     
                            ?>
                        </div>
                    </div>
                <?php
                    }                       
                ?>                   
                <a class="post-like" 
                   rel="<?php print strtolower($likeString); ?>"
                   data-userid="<?php print $userSession->id; ?>"
                   data-postid="<?php print $message['post_id']; ?>"
                   data-posttype="<?php print $message['post_type']; ?>"
                   href="javascript:void(0)">
                    <?php print $likeString; ?>
                </a>
                <a class="post-reply" href="javascript:void(0)">Reply</a>
            </div>    
        </div>
        <?php 
            if(is_array($message['post_children'])) {
                print $this->partial('partial/replies.phtml', array(
                    'children'    => $message['post_children'],
                    'userSession' => $userSession,
                ));
            }
        ?>
        
    </li>
<?php 
    endforeach;
?>
