<?php
    use Zend\Form\Element;
    $errMsg = $form->getMessages();
    $title = 'Add album';
    $this->headTitle($title);
?>               
<span class="site-nav"><a href="<?php echo $this->url('album') ?>">Back</a></span>
<div class="clearfix"></div>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
    $form->setAttribute('action', $this->url('album', array('action' => 'add')));
    $form->setAttribute('class', 'form-horizontal');
    $form->setAttribute('role', 'form');
    $form->prepare();
    print $this->form()->openTag($form);
    
?>
           
<div class="form-group">
    <?php
        $element = $form->get('album_title');
        $element->setLabel('Title:')
                ->setAttribute('id', 'title')
                ->setAttribute('class', 'form-control')
                ->setLabelAttributes(array('class' => 'col-sm-2 control-label'));
        print $this->formLabel($element);
        print '<div class="col-sm-5">';
        print $this->formText($element);
        print '</div>';
        if(isset($errMsg['album_title'])) {
            print $this->errorHelper($errMsg['album_title']);
        }
        
    ?>
</div>
<div class="form-group">
    <?php
        $element = $form->get('album_artist');;
        $element->setLabel('Artist:')
                ->setAttribute('id', 'artist')
                ->setAttribute('class', 'form-control')
                ->setLabelAttributes(array('class' => 'col-sm-2 control-label'));
        print $this->formLabel($element);
        print '<div class="col-sm-5">';
        print $this->formText($element);
        print '</div>';
        if(isset($errMsg['album_artist'])) {
            print $this->errorHelper($errMsg['album_artist']);
        }
             
    ?>
</div>
<div class="form-group">
    <?php
        print '<div class="col-sm-offset-2 col-sm-5">';
        $element = $form->get('fileupload');
        $element->setAttribute('class', 'form-control');
        print $this->formFile($element);
        print '</div>';
        if(isset($errMsg['fileupload'])) {
            print $this->errorHelper($errMsg['fileupload']);
        }
    
    ?>
</div>
<?php
    print '<div class="col-sm-offset-2 col-sm-10">';
    $element = new Element\Button('add-button');
    $element->setLabel("Add")
            ->setAttribute("type","submit")
            ->setAttribute("class","btn btn-default");
    print $this->formButton($element);    
    print '</div>';    
?> 
<?php
    
    print $this->form()->closeTag();    