 <?php
    use Zend\Form\Element;
    use Zend\Permissions\Acl\Acl;
    use Zend\Session\Container;
    use Application\Model\UserRole;
 
 
    $userSession = new Container('user');
    $acl = $this->layout()->acl;
 
    $errMsg = $importForm->getMessages();
    $title = 'My albums';
    $this->headTitle($title);
 ?>
 
<h1><?php echo $this->escapeHtml($title); ?></h1>    

<?php echo $this->partial('partial/upper-line.phtml', 
    array(
        'acl' => $acl,
        'userSession' => $userSession,
        'importForm' => $importForm,
        'exportForm' => $exportForm,
        'searchForm' => $searchForm,
        'orderby' => $orderby,
        'way' => $way)); 
?>
 
<div class="table-responsive">
    <table class="table table-hover table-bordered table-condensed">
        <tr class="success">
         <th>Cover</th>
         <th><?php $sort = $this->sortHelper($orderby, 'album_title', $way); ?>
            <a href="<?php print $sort['url'].'?page='.$page; ?>" 
                title="<?php print $sort['title']; ?>">
                Title
             </a>

         </th>
         <th><?php $sort = $this->sortHelper($orderby, 'album_artist', $way); ?>
             <a href="<?php print $sort['url'].'?page='.$page; ?>" 
                title="<?php print $sort['title']; ?>">
                Artist
             </a>
                
         </th>
         <?php if ($acl->isAllowed($userSession->role, UserRole::ALBUMS_EDIT)) { ?>
             <th>&nbsp;</th>
         <?php } ?>
        </tr>
        
        <?php foreach ($this->paginator as $album) : ?>
        <tr>
             <td>
                 <?php 
                 if (!empty($album->album_img) 
                    && file_exists(ROOT_PATH . '/public/img/albums/'.$album->album_img)) : ?>
                    <img src="<?php print $this->basePath('/img/albums/'.$album->album_img);?>" />
                 <?php else: ?>
                    <img src="<?php print $this->basePath('/img/albums/default.png');?>" />
                 <?php endif; ?>
             </td>
             <td class="text-data">
                <?php print $this->escapeHtml($album->album_title);?>
             </td>
             <td class="text-data">
                <?php print $this->escapeHtml($album->album_artist);?>
             </td>
             <?php  
                if ($acl->isAllowed($userSession->role, UserRole::ALBUMS_EDIT)) { ?>
                
                <td class="edit-link">
                     <a href="<?php print $this->url('album',
                         array('action'=>'edit', 
                               'id' => $album->album_id));?>">Edit</a>
                     <a href="<?php print $this->url('album',
                         array('action'=>'delete', 
                               'id' => $album->album_id));?>" rel="delete">
                               Delete
                     </a>
                 </td>
             <?php } ?>
        </tr>
        <?php endforeach; ?>
    </table>
 </div>
<?php
 // add at the end of the file after the table
    if ($orderby == null) {
        $routeArray = array(
            'route' => 'album',
        );
    } else {
        $routeArray = array(
            'route' => 'sort',
            'order' => $orderby,
            'way' => $way
        );        
    }
    print $this->paginationControl(
        // the paginator object
        $this->paginator,
        // the scrolling style
        'sliding',
        // the partial to use to render the control
        'partial/paginator.phtml',
        // the route to link to when a user clicks a control link
        $routeArray
    );
 ?>
 