<?php 
    use \Zend\Session\Container;
    use \Zend\Permissions\Acl\Acl;
    use \Application\Model\UserRole;    
?>
<?php echo $this->doctype(); ?>
<?php 
    $userSession = new Container('user');
    $acl = $this->layout()->acl;                                
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/jquery.fancybox.css'))
                        ->prependStylesheet($this->basePath('css/jquery-ui.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/my.js'))
            //->prependFile($this->basePath('js/filedrag.js'))
            ->prependFile($this->basePath('js/jquery.postAction.js'))
            //->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.fancybox.pack.js'))
            ->prependFile($this->basePath('js/tmpload.min.js'))
            ->prependFile('http://ajax.aspnetcdn.com/ajax/jquery.templates/beta1/jquery.tmpl.js')
            ->prependFile($this->basePath('js/jquery-ui.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))

        ; ?>

    </head>
    <body>
        <nav class="navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('album') ?>"><img src="<?php echo $this->basePath('img/songs.gif') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Your Favorite Songs:-)') ?></a>
                </div>
                <?php $currentUrl = explode('/',$this->serverUrl(true)); 
                    if(end($currentUrl) != "") {
                ?>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="<?php echo $this->url('album') ?>"><?php echo $this->translate('Home') ?></a></li>
                            <?php  
                                $userRole = new UserRole();
                                
                                if ($acl->isAllowed($userSession->role, UserRole::USERS_INDEX)) { ?>
                                <li><a href="<?php echo $this->url('users') ?>">Users</a></li>
                            <?php } else {?>
                                <li><a href="<?php echo $this->url('users', array('action' => 'edit', 'id' => $userSession->id)) ?>">Manage your account</a></li>
                            <?php } ?>
                            <li><a href="<?php echo $this->url('post') ?>">Posts</a></li>
                            <li class="logout"><span><?php print $userSession->username; ?> is logged</span> <a href="<?php echo $this->url('log', array('action'=>'logout')) ?>">Log out</a></li>
                            
                        </ul>
                            
                    </div>
                <?php } ?><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>

            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
