<?php
    use Application\Model\UserRole;
    use Zend\Session\Container;
    
    $userSession = new Container('user');
    $acl = $this->layout()->acl;                                    
?>
<span class="site-nav">
    <a 
        href="<?php echo $this->url('users', array('action' => 'edit', 
                                                    'id' => $user->id)) ?>" 
        >Back</a>
</span>
<?php if ($acl->isAllowed($userSession->role, UserRole::USERS_INDEX)) { ?>
<span class="site-nav"><a href="<?php echo $this->url('users', array('action' => 'index')) ?>">Users</a></span>
<?php } ?>
<span class="site-nav"><a href="<?php echo $this->url('album') ?>">Albums</a></span>
<div class="clearfix"></div>


<h1>New Generated Password</h1>
<p><?php print $userRole->user_roles_name;?> User <?php print $user->username;?>  has password  <b><?php print $genPass;?></b></p>
<?php if($action == Application\Controller\UserController::ADD) { ?>
    <p><?php print $userRole->user_roles_name;?> User <?php print $user->username;?> has been successfully added to system.</p>        
<?php } else {?>
    <p><?php print $userRole->user_roles_name;?> User <?php print $user->username;?> has been successfully updated.</p>
<?php }?>


